<?php
/**
 * Plugin Name: Who's My Host?
 * Plugin URI: https://www.mattcromwell.com
 * Description: Searching for the holy grail of programmatically knowing which webhost a user is on.
 * Author: webdevmattcrom
 * Author URI: https://www.mattcromwell.com
 * Version: 0.1
 * Text Domain: mc_wmh
 * Domain Path: /languages
 * GitHub Plugin URI: https://github.com/mathetos/Whos-My-Host
 **/

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
// Plugin Folder Path
if ( ! defined( 'MCWMH_FUNCTIONS_DIR' ) ) {
	define( 'MCWMH_FUNCTIONS_DIR', plugin_dir_path( __FILE__ ) );
}
// Plugin Folder URL
if ( ! defined( 'MCWMH_FUNCTIONS_URL' ) ) {
	define( 'MCWMH_FUNCTIONS_URL', plugin_dir_url( __FILE__ ) );
}
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class WhosMyHost {
	private $whos_my_host_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'whos_my_host_add_plugin_page' ) );
	}

	public function whos_my_host_add_plugin_page() {
		add_management_page(
			'Who\'s My Host', // page_title
			'Who\'s My Host', // menu_title
			'manage_options', // capability
			'who-s-my-host', // menu_slug
			array( $this, 'whos_my_host_create_admin_page' ) // function
		);
	}

	public function whos_my_host_create_admin_page() {
		$this->whos_my_host_options = get_option( 'whos_my_host_option_name' );
        $time_start = microtime(true);
		$args = array(
			//formatting
			'strong' => array(),
			'em'     => array(),
			'b'      => array(),
			'i'      => array(),
			'code'      => array(),

			//links
			'a'     => array(
				'href' => array()
			)
		);
		?>
        <div class="wrap">
            <h2>Who's My Host</h2>
            <p>This is where I'll show the info on hosts.</p>
			<?php settings_errors(); ?>

            <table class="form-table">
                <tbody>
                <tr>
                    <th scope="row">DB_HOST</th>
                    <td><?php
						$DBHOST = ( ! empty( 'DB_HOST' ) ? 'DB_HOST' : '<code>DB_HOST</code> is not defined.' );
						echo wp_kses( $DBHOST, $args );
						?><br/>
						<?php
						var_dump( $DBHOST );
						$time1_end = microtime( true );
						$time1     = $time1_end - $time_start;
						?>
                        Time: <?php echo( $time1 * 10000 ); ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row">SERVER</th>
                    <td><?php

						$getserver  = $_SERVER['SERVER_NAME'];
						$the_server = ( ! empty( $getserver ) ? $getserver : '<code>$_SERVER</code> is not defined.' );
						echo wp_kses( $the_server, $args );
						?><br/>
						<?php
						var_dump( $getserver );
						$time2_end = microtime( true );
						$time2     = $time2_end - $time_start;
						?>
                        Time: <?php echo( $time2 * 10000 ); ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row">HTTP_HOST</th>
                    <td><?php
						$http_host = 'HTTP_HOST';
						echo wp_kses( $http_host, $args )
						?><br/>
						<?php
						var_dump( $http_host );
						$time3_end = microtime( true );
						$time3     = $time3_end - $time_start;
						?>
                        Time: <?php echo( $time3 * 10000 ); ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row">gethostname()</th>
                    <td><?php
						$host_name = gethostname();
						echo wp_kses( $host_name, $args )
						?><br/>
						<?php
						var_dump( $host_name );
						$time4_end = microtime( true );
						$time4     = $time4_end - $time_start;
						?>
                        Time: <?php echo( $time4 * 10000 ); ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row">uname()</th>
                    <td><?php
						$u_name = php_uname( 'n' );
						echo wp_kses( $u_name, $args )
						?><br/>
						<?php
						var_dump( $u_name );
						$time5_end = microtime( true );
						$time5     = $time5_end - $time_start;
						?>
                        Time: <?php echo( $time5 * 10000 ); ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row">getenv()</th>
                    <td><?php
						$hostname = getenv( 'HTTP_HOST' );
						echo wp_kses( $hostname, $args )
						?><br/>
						<?php
						var_dump( $hostname );
						$time6_end = microtime( true );
						$time6     = $time6_end - $time_start;
						?>
                        Time: <?php echo( $time6 * 10000 ); ?>
                    </td>
                </tr>
                </tbody>
            </table>

            <div style="max-width: 750px; border: 1px solid #333; padding: 20px; background: #e9e9e9; margin: 20px 0; font-size: 150%; line-height: 1.5rem;">
                <h3>Best guess for your web host:</h3>
                <p><?php echo $this->find_host(); ?></p>
            </div>

            <div style="max-width: 750px; border: 1px solid #333; padding: 20px; background: #e9e9e9; margin: 20px 0; font-size: 150%; line-height: 1.5rem;">
                <h3>INSTRUCTIONS:</h3>
                <ol>
                    <li>Please take a screenshot of this page with your screenshot tool of choice. Just save the image
                        as either a JPG or PNG.
                    </li>
                    <li>Then <a href="https://www.mattcromwell.com/ask-matt/" target="_blank"
                                rel="noopener noreferrer">go here</a> and on the form there, choose "I'm submitting Host Information for
                        you".
                    </li>
                    <li>Submit the form, then reflect on the fact that I REALLY appreciate your help. This little project will help many plugins do a better job of
                        understanding their users and greatly enhance the global WordPress community's ability to
                        troubleshoot plugin/theme issues and communicate effectively with web hosting providers about
                        critical needs.
                    </li>
                </ol>
            </div>
        </div>
	<?php }

	public function is_local() {

	    $is_local = false;
		$getserver  = $_SERVER['SERVER_NAME'];
		$find_local = strpos($getserver, 'local');

		if ( !empty($find_local) ) {
		    $is_local = true;
        }

        return $is_local;
    }

    public function find_host() {
	    $find_host = gethostname();

	    if ( $this->is_local() == true ) {
		    $the_host = "This is a local environment";
		    return $the_host;
		    exit;
	    }

	    $the_host = "We cannot determine your web host. Please mention it in your support ticket.";

        if ( strpos( $find_host, 'sgvps.net') ) {
            $the_host = "Siteground";
        } elseif ( strpos( $find_host, 'fw') ) {
	        $the_host = "Flywheel";
        } elseif ( strpos( $find_host, 'secureserver.net') ) {
	        $the_host = "GoDaddy/Media Temple";
        } elseif ( strpos( $find_host, 'pagelyhosting.com' ) ) {
            $the_host = "Pagely";
        } elseif ( strpos( $find_host, preg_match('wp', $find_host) ) ) {
	        $the_host = "Bluehost";
        }

        return $the_host;

    }

}
if ( is_admin() )
	$whos_my_host = new WhosMyHost();

